webOS-ports/luna-next-cardshell

- qml/CardView/CardGroupListView.qml
> CardView: set a maximum duration for the change of active card

- qml/CardView/CardGroupListView.qml
- qml/CardView/CardGroupModel.qml
- qml/Tests/FakeWindowBase.qml
> CardView: fix window parenting in card stack

- qml/StatusBar/SystemMenu/BluetoothElement.qml
- qml/StatusBar/SystemMenu/BluetoothEntry.qml
- qml/StatusBar/SystemMenu/BrightnessElement.qml
- qml/StatusBar/SystemMenu/MenuDivider.qml
- qml/StatusBar/SystemMenu/Slider.qml
- qml/StatusBar/SystemMenu/SystemMenu.qml
- qml/StatusBar/SystemMenu/VpnEntry.qml
* Fixed wrong maskBottom offset
* Added missing image sizes in Units.gu
* Switched to size in pixels where it is necessary due to border(only
along the vertical)
> Layout improvements to SystemMenu

- qml/LunaSysAPI/VolumeControl.qml
Signed-off-by: Simon Busch <morphis@gravedo.de>
> Adjust VolumeControl to use new VolumeKeys component

- qml/DockMode/DockMode.qml
- qml/Notifications/AlertWindowsArea.qml
To be used together with https://github.com/webOS-ports/luna-webappmanager/commit/923dcf8cb212bc11183cabb07636e6fe29c3ac4e
Note that the requested size is still incorrect -- maybe a DPI issue?
> AlertWindowsArea: fix management of height of alert window

- qml/Notifications/VolumeControlAlert.qml
Need to handle proper connect/disconnect and resubscribe if service comes back.
Signed-off-by: Simon Busch <morphis@gravedo.de>
> Listen for the audio service status

- qml/Notifications/NotificationArea.qml
- qml/Notifications/NotificationTemporaryPopupArea.qml
- qml/Tests/imports/LunaNext/Shell/Notifications/NotificationsListModel.qml
> NotificationArea: add preview of fresh arrived notifications

- qml/CardsArea.qml
- qml/LockScreen/LockScreen.qml
- qml/LockScreen/PasswordField.qml
- qml/LockScreen/PinPasswordLock.qml
> LockScreen: fix keyboard appearance for password pin

- qml/LaunchBar/FullLauncher.qml
> FullLauncher: fix vertical flicking of app grid

- qml/LockScreen/ActionButton.qml
- qml/LockScreen/LockScreen.qml
- qml/LockScreen/MessageDialog.qml
- qml/LockScreen/PasswordField.qml
- qml/LockScreen/PinButton.qml
- qml/LockScreen/PinPad.qml
- qml/LockScreen/PinPasswordLock.qml
Used /8 instead of /10 so sizes were a bit too big
> Fix divider to 10 instead of 8 for proper sizes

- qml/LockScreen/PinButton.qml
> LockScreen: fix delete button image size

- qml/Tests/imports/LunaNext/Common/FontUtilsStub.js
Added additional return values to cater for legacy pt values that couldn't be covered by the few options available. Also updated the existing return values to have more accurate values.
> Added additional return values and corrected the return values

- qml/CardView/CardWindowDelegate.qml
- qml/CardView/CardWindowWrapper.qml
- qml/CardsArea.qml
- qml/LockScreen/LockScreen.qml
- qml/LockScreen/PadLock.qml
- qml/Notifications/AlertWindowsArea.qml
- qml/Notifications/DashboardArea.qml
- qml/OrientationHelper.qml
- qml/StatusBar/SystemIndicators.qml
- qml/WindowManager/OverlaysManager.qml
- qml/main.qml
> Add screen orientation management

- qml/Connectors/BlueToothService.qml
- qml/StatusBar/Indicators/BTIndicator.qml
- qml/StatusBar/SystemIndicators.qml
- qml/StatusBar/SystemMenu/SystemMenu.qml
Still needs backend work for the bluetooth plugin to talk to BlueZ
> Initial work for Bluetooth integration in System Menu/StatusBar

- qml/CardView/CardWindowSplash.qml
> CardView: deactivate splash animation when it isn't visible

- qml/Tests/imports/LunaNext/Common/SettingsStub.js
> Tests: update the Settings test js stub

- qml/Notifications/NotificationArea.qml
- qml/Notifications/NotificationItem.qml
- qml/Notifications/NotificationTemporaryPopupArea.qml
To fix missing icons in case we only have a path.
> Assume icon.png as default icon in case we have a path provided

- qml/CardView/CardView.qml
- qml/CardView/CardWindowWrapper.qml
> CardView: improve CardWindowWrapper instantiation

- README.md
- qml/CardView/CardGroupListView.qml
- qml/CardView/CardView.qml
- qml/CardsArea.qml
> CardView: when in first use mode, always have the current card maximized

- qml/CardView/CardGroupListView.qml
- qml/CardView/CardWindowWrapper.qml
> CardView: fix first steps of a drag event (onEntered). Fixes #939

- qml/CardView/SwipeableCard.qml
> Avoid requesting destruction several times

- qml/CardView/CardView.qml
> CardView: don't focus already focused application

- qml/CardView/CardGroupListView.qml
> CardView: don't put focused card into the front of stack

- qml/CardsArea.qml
- qml/Notifications/AlertWindowsArea.qml
- qml/Tests/FakePopupAlertWindow.qml
> Notifications: add a timeout for banner alerts cards

- qml/Notifications/AlertWindowsArea.qml
> Notifications: fix banner popup height

- qml/CardView/CardView.qml
> Take into account when a window is arisen

- qml/Connectors/BluetoothDevice.qml
- qml/Connectors/BluetoothService.qml
- qml/Connectors/qmldir
- qml/StatusBar/StatusBar.qml
- qml/StatusBar/SystemIndicators.qml
- qml/StatusBar/SystemMenu/BluetoothElement.qml
- qml/StatusBar/SystemMenu/BluetoothEntry.qml
- qml/StatusBar/SystemMenu/SystemMenu.qml
based mostly on
https://github.com/webOS-ports/luna-sysmgr/blob/60c7056a734cdb55a718507f3a739839c9d74edf/Src/lunaui/status-bar/SystemMenu.cpp#L486
using nemo-qml-plugin-dbus
> Further work on bluetooth submenu of SystemMenu

- qml/CardView/CardView.qml
- qml/CardsArea.qml
- qml/Notifications/AlertWindowsArea.qml
- qml/WindowManager/WindowManager.qml
> Notifications: hide alert when tap on gesture area

- qml/DockMode/AnalogClock.qml
- qml/DockMode/Clocks.qml
- qml/DockMode/DigitalClock.qml
- qml/DockMode/DockMode.qml
> DockMode: avoid activating unneeded timers

- qml/Notifications/NotificationArea.qml
> NotificationArea: fix removal of notification

- qml/CardsArea.qml
- qml/Utils/ScreenShooterGradient.qml
> ScreenShooterGradient: code aethetics

- qml/StatusBar/AppMenu.qml
> StatusBar: fix AppMenu

- qml/StatusBar/AppMenu.qml
- qml/StatusBar/StatusBar.qml
> AppMenu: Fix opening by gesture

- qml/Notifications/AlertWindowsArea.qml
- qml/StatusBar/Indicators/BluetoothIndicator.qml
- qml/StatusBar/SystemIndicators.qml
> StatusBar: adapt indicator image to bluetooth status

- qml/LunaSysAPI/Preferences.qml
- qml/StatusBar/SystemMenu/SystemMenu.qml
> SystemMenu: fix rotationLock and muteSound

- qml/Notifications/BannerPopupArea.qml
> Fix playback of banner sound

- qml/WindowManager/OverlaysManager.qml
This PR depends on https://github.com/webOS-ports/luna-next/pull/123
> OverlaysManager: add management for popup overlay type

- qml/CardsArea.qml
- qml/WindowManager/OverlaysManager.qml
> OverlaysManager: use closeWindowWithId to close popup window

- qml/LunaSysAPI/Preferences.qml
- qml/Notifications/BannerPopupArea.qml
Largely based on
https://github.com/openwebos/luna-sysmgr/blob/master/Src/lunaui/notifications/BannerMessageHandler.cpp#L696
and
https://github.com/openwebos/luna-sysmgr/blob/1393f0af5dd8d9f0e9cc79627f4acb226f8c8d45/Src/base/LsmUtils.cpp#L45
converted to JS and made suitable for LNC.
> Rework audio handling for banners

- qml/LaunchBar/Launcher.qml
- qml/LockScreen/Clock.qml
- qml/Notifications/NotificationArea.qml
> Code changes & fixes based on suggestions

- qml/LockScreen/Clock.qml
> Make sure we use the correct separator for the locale + country

- qml/Notifications/BannerPopupArea.qml
> Fix banner showing incorrect :

- qml/StatusBar/SystemMenu/SystemMenu.qml
> SystemMenu: set locked orientation angle properly

- qml/CardView/CardWindowDelegate.qml
- qml/CardView/SwipeableCard.qml
> CardView: have a snappier card swiping behavior

- qml/LaunchBar/LaunchBar.qml
- qml/Tests/default-dock-positions.json
- qml/Tests/default-launcher-page-layout.json
We might need to update this slightly once we have proper localization in place, but this should do it for now.
> Make sure to use the date specific icon for Calendar in LaunchBar

- qml/StatusBar/StatusBar.qml
> StatusBar: fix tablet TweaksClock visibility

- qml/CardShell.qml
> Disable keys handling in firstuse mode

- qml/StatusBar/SystemIndicators.qml
- qml/StatusBar/SystemMenu/BluetoothElement.qml
- qml/StatusBar/SystemMenu/SystemMenu.qml
> Bluetooth: switch to BluezQt

- files/tweaks/luna-next-cardshell.json
> luna-next-cardshell.json: Change Lune OS into LuneOS

- qml/LunaSysAPI/VolumeControl.qml
- qml/Notifications/VolumeControlAlert.qml
- qml/StatusBar/SystemMenu/VolumeElement.qml
To reflect naming changes in audio-service.
> luna-next-cardshell: Update audio-service LS2 calls

- qml/StatusBar/Indicators/BaseIndicator.qml
> BaseIndicator: fix racing condition at initialization

- qml/LunaSysAPI/Preferences.qml
> LunaSysAPI/Preferences: don't try to set preferences before reading them

- qml/LaunchBar/FullLauncher.qml
> FullLauncher: migrate app removal to appinstalld

- qml/CardView/CardGroupListView.qml
- qml/LaunchBar/LaunchableAppIcon.qml
- qml/Utils/ScreenShooterGradient.qml
Since Qt 6.3 this is in Qt5Compat instead
> luna-next-cardshell: Use GraphicalEffects from Qt5Compat instead

- qml/CardView/CardView.qml
> CardView: fallback to card view when no active window found

- qml/CardView/CardGroupListView.qml
- qml/LaunchBar/JustTypeField.qml
Also include more signal signature fixes
> CardGroupListView: fix highlight positioning

- qml/CardsArea.qml
- qml/Notifications/AlertWindowsArea.qml
- qml/Notifications/IconPathServices.qml
- qml/Notifications/NotificationsMergedModel.qml
Currently dashboard windows have the "floating" window type
> Notifications: fix dashboard window detection

- qml/CardShell.qml
partial revert of 1505a29712b87327bb40a178822f17ec067595d6
> CardShell: fix reticle position

- qml/CardView/CardView.qml
- qml/CardView/CardWindowWrapper.qml
- qml/CardsArea.qml
- qml/Tests/default-dock-positions.json
Replace remaining tabs with spaces, in order to provide consistency.
> luna-next-cardshell: Replace tabs with spaces
