- qml/StatusBar/StatusBar.qml
Resubscribing here triggers an indefinite loop and is not necessary.
Signed-off-by: Simon Busch <morphis@gravedo.de>
> Don't resubscribe when telephony service reports noservice

- qml/LaunchBar/FullLauncher.qml
> FullLauncher: reset tab content scroll when hiding full launcher

- qml/LockScreen/LockScreen.qml
> LockMode: Prevent the lock pad to be shown in DockMode state

- qml/Notifications/NotificationArea.qml
So we have the correct icon for banners. We should use the simplest version (miniIcon) where possible.
> Where possible use miniIcon instead of appIcon (for banner)

- qml/LaunchBar/JustTypeField.qml
Power key started to misbehave after QT 5.6 upgrade and would show Just
Type. This will fix it.
> Fix power key handling

- qml/CardShell.qml
- qml/CardView/CardWindowWrapper.qml
- qml/CardsArea.qml
They did more harm then good. This reverts https://github.com/webOS-ports/luna-next-cardshell/commit/1ef6d1078e54016a2f5b0be29190d4d14fc4c6b3
> Revert z-index changes

- qml/CardView/CardGroupListView.qml
usage of functions seems stopped to work for some reason.
Bug #1127.
> CardGroupListView: update Keys.forwardTo manually

- qml/Notifications/AlertWindowsArea.qml
If we call ChangeSize(alertItem.width, window.height) when the window's
height hasn't been updated yet, we will end up with a window of
height zero.
Anyway if window.height <= 0, then onHeightChanged *will* be called
later on, and ChangeSize will actually be applied at that time.
> Notifications: don't resize the client window too soon

- qml/LaunchBar/FullLauncher.qml
- qml/LaunchBar/LaunchableAppIcon.qml
Having {} instead of an empty string would cause weird issues for Enyo 1
app.
> Fix launchParams to be empty to maintain legacy compatibility

- qml/CardView/CardGroupListView.qml
It fixes crashes on emulator in the following scenario:
close web app, quickly open launcher and press esc.
> CardGroupListView: update Keys.forwardTo on cardRemove

- qml/CardView/CardGroupListView.qml
- qml/CardView/CardGroupModel.qml
Fixes crash when window closes itself.
Steps to reproduce crash: open fingerterm, type exit, open launcher and
press esc twice.
> CardView: update Keys.forwardTo on window close

- qml/LunaSysAPI/Preferences.qml
- qml/Notifications/BannerPopupArea.qml
-Ringtone filename should have mp3 extension instead of wav.
-Enyo 2 apps use assets folder, so add these to the paths to search.
> Fix filename for ringtone and add assets path to search

- qml/LaunchBar/Launcher.qml
Let the cardview change the global window state, the Launcher
will then be put in the correct state as a consequence.
> Launcher: don't take action on tap gesture

- qml/Notifications/BannerPopupArea.qml
SMS & IM notifications which use the notification API directly should have
both title and body.
> Add body to the notification

- qml/LaunchBar/LaunchBar.qml
Since we now provide the Phone app on all targets, we need to make sure
we deal with it properly. It seems that Settings.tabletUi is the best
solution for now.
Have the icons like legacy for now.
> LaunchBar: Let Phone app depend on Settings.tabletUi instead & arrange icons.

- qml/LaunchBar/LaunchBar.qml
Fixes: Oct 26 11:38:22 qemux86 mojodb-luna[569]: [] [pmlog] DB8 MOJ_SERVICE_WARNING {"sender":"org.webosports.luna","method":"find","payload":{"query":{"asc":true,"from":"org.webosports.lunalauncher:1","limit":5,"orderBy":"pos"}},"error":"invalid parameters: caller='org.webosports.luna' error='property not allowed - 'asc' for property 'query''","reqErr":22}
> LaunchBar.qml: Don't use asc: true since it's invalid

- qml/CardView/CardGroupListView.qml
Disabling the PinchArea when not in CardView fixes the
pinch-to-zoom feature in the browser.
> CardView: simplify pinch-to-zoom

- qml/Connectors/BluetoothDevice.qml
- qml/Connectors/BluetoothService.qml
Since this was updated in nemo-qml-plugin-dbus.
> Bluetooth: Switch from org.nemomobile.dbus to Nemo.DBus

- qml/StatusBar/SystemIndicators.qml
- qml/luna-next-qml.qmlproject
- qml/mainDesktop.qml
Since Qt 5.8 it wasn't possible to run this on desktop anymore due to
QtWayland.Compositor import. Created a separate mainDesktop.qml without
this import.
> Add mainDesktop.qml

- qml/OrientationHelper.qml
For kms-based eglfs backend, there is no information about rotation
in the screen implementation.
Therefore, to have a generic implementation of the OrientationHelper,
directly fetch the sensor information here and handle it.
> OrientationHelper: don't rely on QScreen anymore

- qml/LaunchBar/LaunchBar.qml
A delegate item might still without a parent, as a Qt optimization to
reuse it later on.
> LaunchBar: fix incorrect parenting

- qml/LaunchBar/LaunchBar.qml
A delegate item might still exist without a parent, as a Qt
optimization to reuse it later on.
> LaunchBar: fix incorrect parenting (bis)

- qml/Connectors/TelephonyService.qml
**Depends on** https://github.com/webOS-ports/webos-telephonyd/pull/19
With improvement from webos-telephonyd, it is now possible to subscribe
to the services even when the service isn't fully initialized yet.
> TelephonyService: subscribe to service as soon as it appears.

- qml/Tests/default-launcher-page-layout.json
After the renaming due to ACG migration.
> default-launcher-page-layout.json: Update appId for Preware

- qml/LockScreen/LockScreen.qml
LockScreen wouldn't show when we would be in FirstUse and screen would turn off and on before completing First Use. We should display lock screen in such case too, otherwise only solution would be to reboot the phone.
> LockScreen: Make sure we display it always even in First Use

- qml/CardView/SwipeableCard.qml
- qml/LaunchBar/FullLauncher.qml
- qml/Notifications/SwipeableNotification.qml
- qml/Utils/FlickableHandleArea.qml
Solves warnings in Qt 5.15+:
QML Binding: Not restoring previous value because restoreMode has not been set.
> luna-next-cardshell: Set restoreMode for Bindings

- qml/StatusBar/SystemIndicators.qml
Seeing we don't have this (yet) in luna-surfacemanager, let's disable it for now.
Solves always visible recording icon and the following in logs:
Apr 30 09:17:18 qemux86-64 surface-manager[581]: [] [pmlog] surface-manager LSM {} (null), file:///usr/lib/qml/WebOSCompositor/qml/StatusBar/SystemIndicators.qml:53:9: Unable to assign [undefined] to bool
> SystemIndicator.qml: Disable the recording indicator

- qml/LunaSysAPI/ApplicationModel.qml
Since sam doesn't provide the API for launchPointChanges, use the one from luna-appmanager instead.
Fixes: May 01 21:36:19 qemux86-64 sam[609]: [] [pmlog] <default-lib> LS_NO_METH {"METHOD":"launchPointChanges"} Couldn't find method: launchPointChanges
> ApplicationModel.qml: Use luna-appmanager for launchPointChanges

- qml/Notifications/NotificationsMergedModel.qml
- qml/SIMPinWindowArea.qml
- qml/WindowManager/OverlaysManager.qml
closeWindowWithId only existed in luna-next, and is now replacd by closeWindow in LSM
> Use closeWindow instead of closeWindowWithId

- qml/Notifications/VolumeControlAlert.qml
This reverts commit 0e8184c27ca6dfa4594e2ed855c27977b47a8941.
The API call was actually correct, but the API declaration in audio-service was not, inducing me in error concerning this call.
> Revert "Fix LS2 call for playFeedback volume change sound"

- qml/LaunchBar/LaunchBar.qml
Not a big fan of the icon for EnactBrowser, but that could be addressed separately.
Fixes:
Oct 24 12:22:29 qemux86-64 surface-manager[503]: [] [pmlog] surface-manager LSM {} (null), file:///usr/lib/qml/WebOSCompositor/qml/LaunchBar/LaunchableAppIcon.qml:44:9: QML QQuickImage: Cannot open: file:///usr/palm/applications/org.webosports.app.browser/icon.png
> LaunchBar.qml: Update Link for Browser

- qml/StatusBar/AppMenu.qml
There is no such item as "appmenu" in most of the appinfo.json files, only very few have it. It's better to use the title instead when available.
Similar is done really in luna-sysmgr: https://github.com/openwebos/luna-sysmgr/blob/master/Src/base/application/ApplicationDescription.cpp#L534
This currently doesn't work yet for native apps such as messwerk, but we can address that later.
> AppMenu.qml: Make sure to set the correct title of the app.

- qml/StatusBar/AppMenu.qml
Look for this appId in the list of the running apps
> AppMenu: add a fallback for apps without any appId

- qml/Connectors/BatteryService.qml
- qml/Notifications/PowerMenu.qml
Since the deprecation of powerd, these calls are now provided by com.webos.service.sleep instead. Old calls still work, but better to update.
For batteryd: Update calls as well to reflect new structure with sleepd, com.webos.service.power2 and com.webos.service.battery
> luna-next-cardshell: Update API calls
